name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: GitHub Stats Card
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          filename: github-metrics.svg
          base: header, activity, community, repositories
          base_indepth: yes
          repositories: 200
          repositories_forks: no

      - name: Top Languages Card
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          filename: languages.svg
          base: ""
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, shell
          plugin_languages_categories: programming
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 2%
          plugin_languages_colors: github
